#!/usr/bin/env bash
output_device="$1"

case $output_device in
  yeti)
    echo "Setting output device to yeti audio headphone jack"
    sink="alsa_output.usb-Blue_Microphones_Yeti_Stereo_Microphone_REV8-00.analog-stereo"
    ;;
  snowball)
    echo "Setting input device to snowball"
    sink="alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201305-00.analog-mono
    ;;
  speakers)
    echo "Setting output device to external speakers"
    sink="alsa_output.pci-0000_00_1b.0.analog-stereo"
    ;;
  *)
    echo "Unknown device mapping, exiting without changing device"
    exit
esac

pacmd set-default-sink $sink
